# Generated by Django 5.2.4 on 2025-08-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default=None, max_length=8),
        ),
    ]
