# Generated by Django 5.2.4 on 2025-08-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('business', 'Business')], max_length=8, null=True),
        ),
    ]
