# Generated by Django 5.2.4 on 2025-08-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
