# Generated by Django 5.2.4 on 2025-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
