# Generated by Django 5.2.4 on 2025-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='profile_pics/'),
        ),
    ]
